### ISSUE TITLE
Test case fail under Linux (Ubuntu)

### ISSUE THREAD

**Issue by davidrupprecht** [proj3rd/tool3rd#21]
Dear @gsongsong,

multiple test cases fail, see below. 

Best regards,
David 

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
 FAIL  test/reducers/counter.spec.ts
  ● Test suite failed to run

    Cannot find module '../../app/features/counter/counterSlice' from 'test/reducers/counter.spec.ts'

      1 | import { AnyAction } from 'redux';
    > 2 | import counterReducer, {
        | ^
      3 |   increment,
      4 |   decrement,
      5 | } from '../../app/features/counter/counterSlice';

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> (test/reducers/counter.spec.ts:2:1)

 FAIL  test/features/counter/Counter.spec.tsx
  ● Test suite failed to run

    Cannot find module '../../../app/features/counter/Counter' from 'test/features/counter/Counter.spec.tsx'

       7 | import { Provider } from 'react-redux';
       8 | import { configureStore } from '@reduxjs/toolkit';
    >  9 | import Counter from '../../../app/features/counter/Counter';
         | ^
      10 | import * as counterSlice from '../../../app/features/counter/counterSlice';
      11 | 
      12 | Enzyme.configure({ adapter: new Adapter() });

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> (test/features/counter/Counter.spec.tsx:9:1)

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.325 s
Ran all test suites.
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
```

**Comment by sjeon87** [comment]
Sorry, those tests have not been updated after creating the project by using `npx creat-react-app`. Therefore, those tests are not valid for the current project. I will update tests on a long-term basis.
